version: "3.2"
services:
  client-dev:
    container_name: client
    build:
      context: sus-client
      dockerfile: Dockerfile.dev
    ports:
      - 8080:8080
    volumes:
      - ./sus-client:/app
    restart: unless-stopped
    depends_on:
      rabbitmq:
        condition: service_healthy
  server-dev:
    container_name: server
    build:
      context: sus-server
      dockerfile: Dockerfile.dev
    volumes:
      - ./sus-server:/app
    restart: unless-stopped
    depends_on:
      rabbitmq:
        condition: service_healthy
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - .data/rabbitmq:/var/lib/rabbitmq/
        - .log/rabbitmq:/var/log/rabbitmq
    healthcheck:
        test: rabbitmq-diagnostics -q ping
        interval: 10s
        timeout: 5s
        retries: 5
  redis:
    image: redis:alpine
    container_name: redis
