@startuml sequence_diagram
participant Web as w
participant Client as c
participant RabbitMQ as q
participant Server as s
participant Redis as r
w -> c: task submission
c -> q: enqueue task
s -> q: dequeue
s <-- q
activate s
deactivate s
s -> r
r --> c
c --> w
@enduml