@startuml sequence_diagram
participant Web as w
participant Client as c
participant RabbitMQ as q
participant Server as s
participant Redis as r
w -> c: GET /u/:shortId
c -> q: enqueue task
s -> q: dequeue
s <-- q
s -> r: get URL
s <-- r
s -> q
q --> c: URL
c --> w: redirect(URL)
@enduml